# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Raster2Vec
                                 A QGIS plugin
 This plugin takes a raster image, and converts it as a vectorial image
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-06-29
        copyright            : (C) 2020 by Paul-Alexandre Nasr
        email                : paul_alexandre99@yahoo.fr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Raster2Vec class from file Raster2Vec.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .raster2vec import Raster2Vec
    return Raster2Vec(iface)
